# Generated by Django 5.0.2 on 2024-02-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0004_document_alter_member_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='path',
            new_name='url',
        ),
    ]
