# Generated by Django 5.0.2 on 2024-02-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0007_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
    ]
