# Generated by Django 5.0.2 on 2024-02-11 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0008_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-date',)},
        ),
    ]
