# Generated by Django 5.0.2 on 2024-03-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0010_event_eventdescription_eventparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photographer', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/event_photo/')),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
