# Generated by Django 5.0.2 on 2024-03-03 22:30

import django.db.models.deletion
import messe_basse_production.models.exposition
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0011_eventphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.CreateModel(
            name='ExpositionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to=messe_basse_production.models.exposition.get_exposition_photo_path)),
                ('order', models.PositiveIntegerField(default=1)),
                ('exposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='messe_basse_production.exposition')),
            ],
        ),
    ]
