# Generated by Django 5.0.3 on 2024-03-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0014_alter_document_file_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/software')),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/software_artist')),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('EN', 'En'), ('FR', 'Fr')], max_length=2)),
                ('description', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='messe_basse_production.software')),
            ],
        ),
    ]
