# Generated by Django 5.0.3 on 2024-03-12 12:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0015_software_softwareartist_softwaredescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/artist')),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('main_link', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='softwaredescription',
            old_name='event',
            new_name='software',
        ),
        migrations.AlterField(
            model_name='eventdescription',
            name='lang',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French')], max_length=2),
        ),
        migrations.AlterField(
            model_name='softwaredescription',
            name='lang',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French')], max_length=2),
        ),
        migrations.CreateModel(
            name='ArtistDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'French')], max_length=2)),
                ('description', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='messe_basse_production.artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AM', 'Amazon'), ('AP', 'Apple'), ('BC', 'Bandcamp'), ('DZ', 'Deezer'), ('DC', 'Discogs'), ('FB', 'Facebook'), ('FL', 'Flickr'), ('GH', 'Github'), ('IG', 'Instagram'), ('LI', 'Linkedin'), ('MC', 'Mixcloud'), ('SC', 'Soundcloud'), ('SP', 'Spotify'), ('TD', 'Tidal'), ('TW', 'Twitter'), ('YT', 'Youtube')], max_length=2)),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='messe_basse_production.artist')),
            ],
        ),
    ]
