# Generated by Django 5.0.3 on 2024-03-12 13:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0016_artist_rename_event_softwaredescription_software_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('name', models.CharField(max_length=150)),
                ('catalog', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='images/release')),
                ('main_link', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='messe_basse_production.artist')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AM', 'Amazon'), ('AP', 'Apple'), ('BC', 'Bandcamp'), ('DZ', 'Deezer'), ('DC', 'Discogs'), ('FB', 'Facebook'), ('FL', 'Flickr'), ('GH', 'Github'), ('IG', 'Instagram'), ('LI', 'Linkedin'), ('MC', 'Mixcloud'), ('SC', 'Soundcloud'), ('SP', 'Spotify'), ('TD', 'Tidal'), ('TW', 'Twitter'), ('YT', 'Youtube')], max_length=2)),
                ('url', models.URLField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='messe_basse_production.release')),
            ],
        ),
    ]
