# Generated by Django 5.0.3 on 2024-03-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0018_alter_eventphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='release',
            name='artist',
        ),
        migrations.AddField(
            model_name='release',
            name='artist',
            field=models.ManyToManyField(related_name='releases', to='messe_basse_production.artist'),
        ),
    ]
