# Generated by Django 5.0.3 on 2024-03-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0019_alter_document_options_remove_release_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='artist_names',
        ),
    ]
