# Generated by Django 5.0.3 on 2024-06-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messe_basse_production', '0021_rename_artist_release_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'French')], max_length=2)),
                ('description', models.TextField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='messe_basse_production.podcast')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('catalog', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='images/podcast')),
                ('link', models.URLField()),
                ('podcast', models.ManyToManyField(related_name='podcasts', to='messe_basse_production.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastEpisodeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'French')], max_length=2)),
                ('description', models.TextField()),
                ('podcast_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='messe_basse_production.podcastepisode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AM', 'Amazon'), ('AP', 'Apple'), ('BC', 'Bandcamp'), ('DZ', 'Deezer'), ('DC', 'Discogs'), ('FB', 'Facebook'), ('FL', 'Flickr'), ('GH', 'Github'), ('IG', 'Instagram'), ('LI', 'Linkedin'), ('MC', 'Mixcloud'), ('SC', 'Soundcloud'), ('SP', 'Spotify'), ('TD', 'Tidal'), ('TW', 'Twitter'), ('YT', 'Youtube')], max_length=2)),
                ('url', models.URLField()),
                ('podcast_episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='messe_basse_production.podcastepisode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
